### ISSUE TITLE
Create data models for rules engine

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#106]
Refactor the rules engine into input and output data models. This will make it easier to standardize/validate input/output and possibly reuse data structures for persistence.

**Comment by jkwan2011** [comment]
Currently working on refactoring rules engine to add Pydantic models in #77.

**Comment by debajyotid2** [comment]
> Currently working on refactoring rules engine to add Pydantic models in #77.

Should we close this issue now that we have merged https://github.com/codeforboston/home-energy-analysis-tool/pull/77?
