### ISSUE TITLE
Create a function to determine inclusion enum for a given date

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#107]
As part of the calculation for natural gas, the rules engine needs to be able to categorize dates into winter months (INCLUDE), summer months (INCLUDE IN OTHER ANALYSIS), and shoulder months (DO NOT INCLUDE). Finish developing and testing the `date_to_analysis_type` function based on the month-to-enum map provided.

**Comment by alanisaac** [comment]
The function should mimic the logic from column F in the Natural Gas sheet in the Excel spreadsheet.  This logic references the "Lookup" hidden sheet that has the provided month-to-enum mapping.
