### ISSUE TITLE
Finish rework on initialize billing periods

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#119]
Finish changes to initialize billing periods function, previously on [lines 258-297](https://github.com/codeforboston/home-energy-analysis-tool/commit/2fecc0e3d6be7396618473449e3cd4e2dc24adf7#diff-f791e1610ac332ea881dedad4d352fd2bd768ee38988bd7702c0b0873d3a2d84L258-L298), with an additional comment on [lines 332-331](https://github.com/codeforboston/home-energy-analysis-tool/commit/2fecc0e3d6be7396618473449e3cd4e2dc24adf7#diff-f791e1610ac332ea881dedad4d352fd2bd768ee38988bd7702c0b0873d3a2d84L323-L332).

**Comment by harryzhu626** [comment]
on it!

**Comment by alanisaac** [comment]
No longer needed on the latest code.
