### ISSUE TITLE
Calculate heating degree days (HDD) based off of billing period

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#12]
Calculate daily heating usage for each period, defined as average daily total usage minus average non-heating usage
- For gas, average non-heating usage is calculated as average daily usage where inclusion code = -1 (summer months)

For each period with an inclusion code of 1, calculate the period Heating Degree Day (HDD) by summing the daily HDDs within the period (average daily temp minus balance point) given a user-specified balance point.
- Balance point: Temp inside of home at which no heating is required.

Calculate the UA for each period: days in bill * daily heating usage * fuel BTU per usage unit * heating system efficiency / (period HDD*24)

**Comment by plocket** [comment]
Repeat this until a lowest standard deviation is found.
