### ISSUE TITLE
CSV parsing for natural gas billing inputs

### ISSUE THREAD

**Issue by alanisaac** [codeforboston/home-energy-analysis-tool#121]
The javascript team would like the rules engine to do CSV parsing for the time being for Natural Gas billing inputs.  Implement this as a layer on top of the existing rules engine code.

**Comment by erika-n** [comment]
Is this still applicable? The Javascript will have to load the CSV into the interface before it is sent to the rules engine.

**Comment by alanisaac** [comment]
We checked in with the JS team this week and confirmed that:

* On the first run, the JS team will loads the CSV into a string, and pass it to the rules engine
* The rules engine will return billing period output to populate the billing period table
* Subsequent runs will pass those object models, with user tweaks (like inclusion overrides) back to the rules engine

**Comment by alanisaac** [comment]
The parser should be able to handle CSVs from both Eversource and National Grid, and the formats for each are slightly different.

**Comment by jkwan2011** [comment]
Examples of each file type can be found here: https://drive.google.com/file/d/1vqfbl1VerpECJspUKxGwJs3RQzCveUEW/view?usp=drive_link
