### ISSUE TITLE
Integrate weather API into rules engine

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#122]
Weather data will need to be called from the Javascript API and sent to the rules engine.

**Comment by thadk** [comment]
@plocket We should take these three APIs outputs and prepare something we can pass to python for the weather:
 https://github.com/codeforboston/home-energy-analysis-tool/issues/20#issuecomment-1707485014

**Comment by erika-n** [comment]
We have input classes that should be the same as the shape of the data returned by the API
