### ISSUE TITLE
Finish balance point graph outputs

### ISSUE THREAD

**Issue by alanisaac** [codeforboston/home-energy-analysis-tool#129]
Today, the rules engine does not output data to produce a balance point graph.  We did not initially because it was believed this was one of the steps the rules engine was meant to automate away.

However, recent designs from the design team show these same graphs.  We would like to refactor the rules engine to be able to output these data points as part of its calculations.

**Comment by erika-n** [comment]
The logic is in the rules engine but the output is not being returned because the graph is not included in the current design.
