### ISSUE TITLE
Ouput AnalysisType for UI

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#137]
The UI needs to display to the user whether each line of a given billing period is included or excluded, and if included, whether it is included for heating usage or non-heating usage. Create a new output data structure and function to return this data to the user.

**Comment by David-Egan** [comment]
Is there a reason we cannot pass period_start_date and period_end_date to BillingPeriods when constructing them (so the UI can identify and display the billing periods) and return all BillingPeriods (which should already have an assigned analysis type) from the Home object to accomplish this?

**Comment by David-Egan** [comment]
Took a stab at this in #142 but I'm not sure if that's the exact approach we want, happy to modify the approach.

**Comment by erika-n** [comment]
See also #111 and #96 (other things to include about each billing period)
