### ISSUE TITLE
Data persistence and offline support

### ISSUE THREAD

**Issue by clayton-schneider** [codeforboston/home-energy-analysis-tool#138]
At the moment the initial design from the design team is being consolidated into one page.

Below are a few candidates we considered on how we can persist data when there is no DB or access to internet.
- Thad found this article regarding what PWA's can do: [https://whatpwacando.today/](https://whatpwacando.today/) and then how you can implement it in [Remix](https://remix-pwa.run/)
- We considered using cookies to persist data from the server to the client, while there is no DB: [here is a link](https://remix.run/docs/en/main/utils/sessions#using-sessions)
- We also considered using local storage, which looks like is not accessible by PWA

**Comment by thadk** [comment]
I also made an unfinished, but basically working example repo for remix-pwa at https://github.com/thadk/epic-stack-with-remix-pwa

**Comment by thadk** [comment]
We decided to have a single page form so this is closed until we need to divide the form up again.
