### ISSUE TITLE
Calculate and output heat pump metrics

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#15]
- Calculate average indoor temp: ((24 - setback hrs per day) * tstat setting + setback hrs per day * setback temp)/24
- Calculate avg heat load: (design set point - (avg indoor temp - balance point) - design temp) * UA
- Calculate max heat load: (design set point - design temp) * UA

**Comment by mciethan** [comment]
fixed by #52
