### ISSUE TITLE
Link js/python READMEs in the project's top level README

### ISSUE THREAD

**Issue by thatoldplatitude** [codeforboston/home-energy-analysis-tool#152]
This repo has a README in the top level,heat-stack, and rules-engine directories. Add a link in the top level README to the others, so people can be more easily directed.

**Comment by thadk** [comment]
#151 these issues refer to the same topic

**Comment by thatoldplatitude** [comment]
Duplicate of #151 
Oops sorry, missed that. I'll close this in favour of #151 , Ik someone had expressed interest in taking this on.
