### ISSUE TITLE
Handle null temperature data

### ISSUE THREAD

**Issue by alanisaac** [codeforboston/home-energy-analysis-tool#166]
* The javascript code gets weather data that has possibly null temperature data, possibly because the data source does not have data for today's temperatures. 
* The rules engine team expects temperature data to exist.

Figure out what to do here.  cc: @plocket @thadk

**Comment by AdamFinkle** [comment]
For now, we have chosen to throw an exception when any null temperature value is given.  It is possible to ultimately fix this problem at the javascript level by fetching the missing temperature data from the open-meteo api.
