### ISSUE TITLE
Remove Git LFS

### ISSUE THREAD

**Issue by AdamFinkle** [codeforboston/home-energy-analysis-tool#178]
Git Large File System is required for our repository although none of the files requires it anymore.  I have searched the issues list for LFS and seen that #88 may be connected.

**Comment by thadk** [comment]
Thanks Adam, we opted for a different approach for #88 so we will not store the rules engine wheel inside the repository at all. We can turn off Git LFS for the repository if someone can figure out how, and submit a PR.

**Comment by thadk** [comment]
This 2mb file is saved as ifs: https://github.com/codeforboston/home-energy-analysis-tool/blob/7555497d80ca6cb574b97c5626c4d48cfa54f137/design_temp/ENERGY%20STAR%20Certified%20Homes%20County-Level%20Design%20Temperature%20Reference%20Guide.pdf#L2

**Comment by AdamFinkle** [comment]
This [branch](https://github.com/AdamFinkle/home-energy-analysis-tool/tree/remove_lfs2) should have LFS turned off, but it requires rewriting **every** commit, requiring all PRs to be submitted before we do it.  Follow this [Phind](https://www.phind.com/search?cache=cp13gibwkmaq2ec7etiol8o4) exactly to replicate the steps, which you must do after submitting every PR you want to keep because these changes rewrite almost every commit.

**Comment by thadk** [comment]
https://github.com/codeforboston/home-energy-analysis-tool/pull/140#issuecomment-2148693591
