### ISSUE TITLE
Stand up codespaces for collaborative development

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#18]
In order to facilitate ensemble programming, set up codespaces, and share information of what is needed to start using them.

**Comment by thadk** [comment]
Please try this codespace out

**Comment by jkwan2011** [comment]
Documentation for using Codespaces:
1. From the GitHub project page, click on the green Code button -> Codespaces -> Create codespace...
2. Once the Codespace has been created, click on Extensions in the left toolbar and install the Live Share extension
3. Click the Live Share button at the bottom of the window to activate the extension
4. Enable access to the Live Share by going to the Ports tab in the new section, right-clicking on the appropriate port and changing "Port Visibility" to Public
5. Install other tools as needed into the development environment (npm, etc.)
6. Copy and share link to invite others to join the session, accepting read-write permissions for all participants

**Comment by jkwan2011** [comment]
Created wiki page with documentation: https://github.com/codeforboston/home-energy-analysis-tool/wiki/Development-Environment#github-codespaces
