### ISSUE TITLE
Investigate method for looking up weather station data

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#20]
We need to look up weather station data for the calculation of heat degree days.  There are APIs online (e.g. https://www.degreedays.net) that might be able to help.
- Obtained from an API (either degree days or visual crossing or some other), and likely called from Javascript
- How do we get location information? Is it provided by the user?
- Consider how does this interact with a client-side offline-first app? Instructions to cache data on the device?
- Consider licensing and pricing model

**Comment by thadk** [comment]
Use Archive to retrieve archival weather (do not use for last 6-7 days of weather)
- **Historical archival records API**: https://archive-api.open-meteo.com/v1/archive?latitude=52.52&longitude=13.41&daily=temperature_2m_max&timezone=America%2FNew_York&start_date=2022-01-01&end_date=2023-08-30&temperature_unit=fahrenheit
- **Current week forecast API**: https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=temperature_2m_max&timezone=America%2FNew_York&past_days=5&forecast_days=1&temperature_unit=fahrenheit

**Comment by plocket** [comment]
We're using `useLoader` for now.
