### ISSUE TITLE
Better Pyodide setup in the NextJS app

### ISSUE THREAD

**Issue by thadk** [codeforboston/home-energy-analysis-tool#29]
### Enhancements for #28 
Open for anyone if you can follow any of my points below:

- [ ] Try the native import as suggested by [this SO question](https://stackoverflow.com/questions/75310292/how-can-i-include-files-from-node-modules-in-my-next-js-build-so-that-they-can-b#) now that I put the files in the correct place (`/public/`)
    -  will need to uncomment some `loadPyodide` code showing JS where that is: 
- [ ] If that works, remove the `<Script/>`  ([docs](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts)) and comments. Otherwise keep as-is but remove comments.
- [ ] With either working `import` approach, make a component maybe [like this code style](https://github.com/xhluca/react-pyodide-template/blob/main/src/App.js#L15-L36) to display the python output from a `.py` file in a react component instead of in console.

![image](https://github.com/codeforboston/home-energy-analysis-tool/assets/283343/c458fcf6-5fc5-471e-a3c6-d38d1cfdb7c1)

**Comment by spghtti** [comment]
Pyodide kept throwing a `Cannot determine runtime environment` error when doing a native import so I went with using the `Script` tag. 

I found an open issue with someone encountering the same thing on pyodide/Next.js. https://github.com/pyodide/pyodide/issues/3893
