### ISSUE TITLE
Clean up example.py

### ISSUE THREAD

**Issue by alanisaac** [codeforboston/home-energy-analysis-tool#35]
The example Python file and associated tests were created as a means to set up our build and test CI pipelines.  Now that we have actual code and actual tests for our rules engine, these are no longer needed.

Delete the following files:
* https://github.com/codeforboston/home-energy-analysis-tool/blob/main/rules-engine/src/rules_engine/example.py
* https://github.com/codeforboston/home-energy-analysis-tool/blob/main/rules-engine/tests/rules_engine/test_example.py

**Comment by JesusC-R** [comment]
Please assign this task to me

**Comment by mciethan** [comment]
fixed on main
