### ISSUE TITLE
Suggestion: use an enum for fuel types

### ISSUE THREAD

**Issue by alanisaac** [codeforboston/home-energy-analysis-tool#45]
In order to prevent developer error, convert places where we define `fuel_type` from a string to a Python [enum](https://docs.python.org/3/library/enum.html).

**Comment by mciethan** [comment]
Agreed that an enum makes sense for fuel types. One important property for a fuel type enum to have is BTU_per_usage, which is a numerical constant associated with each enum that is used to convert its unit of usage into BTUs. Those values are currently hard-coded into the bp_ua_estimates() method of engine.py

**Comment by mciethan** [comment]
fixed by 4fe1238
