### ISSUE TITLE
Experiment: Try loading multiple Python modules in Pyodide

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#53]
If we split the rules engine into multiple files, will Pyodide be able to load the modules correctly?

Try creating one Python file that loads another one (through import).  Try loading the first file with Pyodide.  Is the second module available for use, or does that file have to also be loaded separately with Pyodide?

**Comment by thadk** [comment]
Presently each file gets loaded into javascript as a string and then sent to the pyodide interpreter. 

If y'all generate a python package for your project ([ideally with no fancy binary dependencies](https://pyodide.org/en/stable/usage/loading-packages.html#micropip)— "pure Python wheels" in the lingo), that can be imported  by URL of the generated whl file with `micropip`.

**Comment by alanisaac** [comment]
For testing, we can try out loading across files in the same package using the code in the above PR (#78).  If that doesn't work, we can go with wheels.

**Comment by jkwan2011** [comment]
Python imports tested #83.
