### ISSUE TITLE
Investigate how to call the rules engine from the front-end

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#64]
Investigate handling for calling rules engine:
- [x] Determine whether to deliver the rules engine as a single file, or to package it as a wheel. Front end #83.
- [x] Figure out what can be passed back and forth between the front-end and the rules engine (can we do objects, or do we have to use primitives?) #66

**Comment by jkwan2011** [comment]
Maybe use `Proxy`

**Comment by plocket** [comment]
For the second, we can use instantiated classes (python objects).

**Comment by plocket** [comment]
Rules engine has merged example of multiple files into main.

**Comment by alanisaac** [comment]
From what I understand, testing showed us that we need the wheel to split the rules engine into multiple files.  Since this is desirable for the rules engine, I've logged #88 for us to build a wheel.  I think that closes out the investigation for this task.
