### ISSUE TITLE
Add data validation for rules engine

### ISSUE THREAD

**Issue by jkwan2011** [codeforboston/home-energy-analysis-tool#74]
Input to the rules engine should be validated:
- Move the data models from the `test_examples` into the rules engine (will require restructuring of test input data)
- Move validation from `test_examples` into rules engine
- Add new validation as appropriate

**Comment by jkwan2011** [comment]
- Separate out the data objects into separate classes (e.g., outdoor temperature, billing period usage)
- Evaluate operations performed on data and restructure classes if necessary (for instance, take a look if the functions called in the initialization of `BillingPeriod` should be moved elsewhere)
- Investigate how fuel data will be input into the rules engine (i.e., will it be parsed by the Javascript or does it need to be validated by the Python)

**Comment by jkwan2011** [comment]
Data models broken out into #106.

**Comment by alanisaac** [comment]
Validation is provided by the Pydantic models.
