### ISSUE TITLE
Frontend: Test pyodide multiple files

### ISSUE THREAD

**Issue by plocket** [codeforboston/home-energy-analysis-tool#83]

**Comment by plocket** [comment]
Results: When we tried to use both `import_test_1` and `import_test_2` we got an error. When we used just `import_test_2` it worked just fine.

Conclusion:
- The rules engine team can make separate files for functionality that is completely separate. The js can then use whatever is in each of those files.
- The rules engine team is unable to import one python file into another.

@jkwan2011, is this what you're asking about?

**Comment by jkwan2011** [comment]
Thanks for the test! I think we can stick with one file for now. We can call it a stretch goal to use a wheel file, but I think that might be a task for want of a DevOps engineer.
