### ISSUE TITLE
Build a wheel and add to Git LFS

### ISSUE THREAD

**Issue by alanisaac** [codeforboston/home-energy-analysis-tool#88]
The front end did some testing and needs a wheel if we want to split into multiple files.  Build a wheel!

**Comment by thadk** [comment]
Please place the wheel file in `heat-stack/public`

**Comment by jkwan2011** [comment]
CI for build has been added in #90, but since no CD yet, will have to manually deploy to location above. Add wheel file to Git LFS.

**Comment by alanisaac** [comment]
Steps to build the wheel:

Check that you are on the same version of Python that we want to run in `pyodide` with:

```py
python --version
```

Then build the wheel:

```py
cd rules-engine
pip install -q build
python -m build
```

The wheel should output at:

```
rules-engine\dist\rules_engine-0.0.1-py3-none-any.whl
```
